In [1]:
import numpy as np

In [5]:
a = np.arange(1,9,1.5) #works as range in python(start,end,step size) and also allow float value
a

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [6]:
b = np.array([1,10,100]) #provide range manually
b

array([  1,  10, 100])

In [7]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a = a.reshape(4,3) # reshape(rows,columns) reshape works as immutable

In [11]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
a*2  #mathematical behaviour of numpy (its multiply every item by 2)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [18]:
q = np.array([1.5,0,-1,100], dtype = 'int8')
q

array([  1,   0,  -1, 100], dtype=int8)

In [19]:
q*2 # -56 means tha first bit is sign and remaing can be calculated by 2's complement

array([  2,   0,  -2, -56], dtype=int8)

In [22]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
arr[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [26]:
arr[:,-1]

array([ 3,  7, 11])

In [28]:
c = np.arange(24).reshape(2,3,4) #(depth,rows,columns) ## 3D or multi-dimensions means tensors
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
c[1,1,1]

17

In [30]:
c[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
d = c.reshape(24) #convert tensor to vector
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
d = c.reshape(-1) #convert tensor to vector
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
c.flatten()  #convert tensor to vector using function flatten


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
c1 = np.arange(24).reshape(-1,6) #numpy automatically check the parameter if one parameter is unknown or not given (like -1)
c1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## Vectorization / Mapping / Broadcasting
if one function is applied to every item in an array. this is called Vectorization.

In [40]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
b*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [44]:
b+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
b**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [46]:
b>5 #it is not filter the value instead it provide boolean value 

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

## Masking/Filtering

In [47]:
b>5 #it is not filter the value instead it provide boolean value 

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [48]:
b[b>5]

array([ 6,  7,  8,  9, 10, 11])

In [49]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [50]:
b = np.arange(4) + 10
b

array([10, 11, 12, 13])

In [51]:
a*b ##element wise multiplication (must have same size)

array([ 0, 11, 24, 39])

In [52]:
a.dot(b) ## multiplication of two vector is scalar

74

In [53]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[1,2]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[1 0]
 [1 2]]


In [54]:
A*B

array([[1, 0],
       [3, 8]])

In [55]:
A.dot(B)

array([[3, 4],
       [7, 8]])

In [56]:
A = np.arange(3).reshape(1,3)
A

array([[0, 1, 2]])

In [57]:
B = np.arange(3).reshape(3,1)
B

array([[0],
       [1],
       [2]])

In [58]:
A.dot(B)

array([[5]])

In [59]:
B.dot(A)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

## Special Arrays

In [62]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.ones((3,4)) *-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [65]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.linspace(1,5,9) #(start,end,number of chuncks) means linear space value

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [69]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.max(b)  #print maximum value of vextor/matrix

11

In [71]:
np.sum(b) #print sum value of vextor/matrix

66

In [72]:
np.max(b,axis=0) #means which axis pass will be merged and remaining axis exist (0= rows, 1 = columns)

array([ 8,  9, 10, 11])

In [73]:
np.sum(b,axis=1)

array([ 6, 22, 38])

In [74]:
np.mean(b,axis = 0)

array([4., 5., 6., 7.])

In [75]:
np.median(b, axis=1)

array([1.5, 5.5, 9.5])

In [76]:
np.std(b) ##standard deviation tells how much data is spread. low std means data centered around mean and high means data is spread  large

3.452052529534663

In [77]:
import time

In [86]:
time.time() #unix time or Epoch time starting from 1st jan 1970 midtime(GMT)

1578815776.0374908

In [91]:
np.random.rand(1) #it take input as epoch time and generate random value

array([0.67793722])

In [93]:
np.random.rand(1) * 100

array([45.83972083])

In [94]:
90 + np.random.rand(1) * 10 #scaling

array([91.48809095])

In [89]:
np.random.rand(4,3)

array([[0.43668401, 0.04287173, 0.4874663 ],
       [0.55559168, 0.13491651, 0.75816473],
       [0.51180445, 0.74379702, 0.7729232 ],
       [0.1961496 , 0.18679594, 0.21907281]])

In [96]:
np.random.randint(5,10,10)  # (start,end,number of items generated) #it uses uniform distribution

array([6, 8, 9, 5, 7, 6, 7, 7, 6, 9])

In [98]:
mu=100 #mean
sigma = 15  #std
s = np.random.normal(mu,sigma,100)  #normal distribution 

In [100]:
np.mean(s)

101.8775527582779

In [101]:
np.std(s)

15.333966600787427

101.8775527582779