In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 


In [2]:
from sklearn.datasets import load_iris

In [5]:
dataset = load_iris()

In [6]:
dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [21]:
dataset['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
x = dataset['data']
print(x.shape)

(150, 4)


In [10]:
y = dataset['target']
print(y.shape)

(150,)


In [11]:
dataset['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(x,y)

In [17]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(112, 4) (112,)
(38, 4) (38,)


# model fitting 

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [19]:
knn.score(X_train, y_train)

0.9821428571428571

In [20]:
knn.score(X_test, y_test)

0.9210526315789473

# Prediction

In [23]:
knn.predict([[5.1, 3.5, 1.4, 0.2]])

array([0])

In [27]:
dataset['target_names'][0]

'setosa'

In [28]:
pred = knn.predict(X_test)

In [29]:
pred[:10]

array([2, 1, 1, 0, 0, 0, 1, 1, 0, 0])

In [30]:
y_test[:10]

array([2, 2, 1, 0, 0, 0, 2, 1, 0, 0])

In [33]:
demo  = np.array([[6.7, 3.3, 5.7, 2.1]])
print(f"shape={demo.shape}")

pred = knn.predict(demo)

print(f"Predicted flower : {dataset['target_names'][pred]}")

shape=(1, 4)
Predicted flower : ['virginica']


perform same task using Logistic regression to improve the accurecy

In [34]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

c:\users\lenovo\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
lr.score(X_train, y_train)

0.9642857142857143

In [36]:
lr.score(X_test, y_test)

0.9210526315789473

In [37]:
pred = lr.predict(X_test)

In [38]:
pred

array([2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 2, 0, 2, 2, 1,
       2, 1, 2, 0, 2, 1, 2, 1, 1, 2, 0, 1, 0, 0, 1, 2])

In [39]:
y_test

array([2, 2, 1, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 2, 0, 2, 2, 1,
       2, 1, 2, 0, 2, 2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 2])

In [ ]:
KMEANS