In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('50_Startups MLR.csv')

In [4]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
data.shape

(50, 5)

In [16]:
real_x = data.iloc[:,0:4].values
real_y = data.iloc[:,-1].values
real_x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

# NOw PerForm_Label_InCOding

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
real_x[:,3] = le.fit_transform(real_x[:,3])
real_x[:,3]

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0], dtype=object)

# NOw cONVert it into BiNAry FoRmate

In [8]:
from sklearn.preprocessing import OneHotEncoder
onhe = OneHotEncoder()
real_x = onhe.fit_transform(real_x).toarray()

In [10]:
real_x

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

# SplLitting DataSet

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train , X_test , y_train, y_test =  train_test_split(real_x, real_y)

In [15]:
X_train.shape, y_train.shape, 

((37, 150), (37,))

# ApplYING REGression  Model 

In [20]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(X_train, y_train)
print(f"the accuracy in training dtatadset {mlr.score(X_train, y_train)}")
print(f"the accuracy in testing dataset {mlr.score(X_test, y_test)}")

the accuracy in training dtatadset 1.0
the accuracy in testing dataset -0.3955460825407271


In [21]:
y_pred = mlr.predict(X_test)

In [22]:
y_test

array([146121.95, 110352.25,  69758.98, 132602.65, 108552.04, 155752.6 ,
       124266.9 , 191792.06,  64926.08, 192261.83, 118474.03,  96778.92,
       156122.51])

In [23]:
y_pred

array([112378.71506526, 112378.71506526, 115607.74523928, 112378.71506526,
       115607.74523928, 112378.71506526, 112378.71506526,  98427.71554382,
       115607.74523928, 115607.74523928,  98427.71554382, 112378.71506526,
        98427.71554382])